name: Build and deploy Node.js app to Azure Web App - EulaIQ-Api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm' # Cache npm dependencies for faster builds

      - name: Install dependencies and build
        run: |
          npm ci # Use npm ci for consistent installs in CI
          npm run build --if-present # Run build if a build script exists
          npm run test --if-present # Run tests if a test script exists

      - name: Create deployment package
        run: |
          mkdir deployment
          # Copy essential files, excluding node_modules
          cp -r package*.json ./deployment/
          cp -r server.js ./deployment/ || true
          cp -r index.js ./deployment/ || true
          cp -r app.js ./deployment/ || true
          cp -r Models ./deployment/ || true
          cp -r Controllers ./deployment/ || true
          cp -r Routers ./deployment/ || true
          cp -r Middlewares ./deployment/ || true
          cp -r Helpers ./deployment/ || true
          cp -r Services ./deployment/ || true  # Add this line to include Services directory
          cp -r data ./deployment/ || true
          cp -r public ./deployment/ 2>/dev/null || true
          cp -r dist ./deployment/ 2>/dev/null || true
          # Zip the deployment folder
          cd deployment && zip -r ../release.zip ./* && cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for Azure login with OIDC
      contents: read # Required for downloading artifacts

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F1E0D69D49BA43F7859790B396A6603B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3BADDA795BBF415B9749AC67A4425166 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AE26D494972F474EB74E28A44D1611F6 }}

      - name: Set startup command
        run: |
          az webapp config set --resource-group EulaIQ-Server --name EulaIQ-Api --startup-file "npm install && npm start"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EulaIQ-Api'
          package: release.zip