# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - EulaIQ-Api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'  # Added caching for faster builds

      - name: npm install, build, and test
        run: |
          npm ci  # More reliable than npm install for CI environments
          npm run build --if-present
          npm run test --if-present

      - name: Create deployment package
        run: |
          # Create a clean deployment directory
          mkdir deployment
          
          # Copy necessary files (adjust as needed for your application)
          cp -r package*.json ./deployment/
          cp -r node_modules ./deployment/ 2>/dev/null || true
          cp -r server.js ./deployment/ || true
          cp -r index.js ./deployment/ || true
          cp -r app.js ./deployment/ || true
          cp -r Models ./deployment/ || true
          cp -r Controllers ./deployment/ || true
          cp -r Routers ./deployment/ || true
          cp -r Middlewares ./deployment/ || true
          cp -r Helpers ./deployment/ || true
          cp -r data ./deployment/ || true
          cp -r public ./deployment/ 2>/dev/null || true
          cp -r dist ./deployment/ 2>/dev/null || true
          
          # Create a smaller zip with only required files
          cd deployment && zip -r ../release.zip ./* && cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F1E0D69D49BA43F7859790B396A6603B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3BADDA795BBF415B9749AC67A4425166 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AE26D494972F474EB74E28A44D1611F6 }}

      - name: Stop Azure Web App before deployment
        run: |
          az webapp stop --name EulaIQ-Api --resource-group EulaIQ-Server
          # Wait a moment for the app to fully stop
          sleep 10
        continue-on-error: true

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EulaIQ-Api'
          publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE }}
          package: .
          clean: true

      - name: Start Azure Web App after deployment
        run: |
          az webapp start --name EulaIQ-Api --resource-group EulaIQ-Server
        continue-on-error: true
